# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Thu Apr 22 16:15:08 2010
#      by: PyQt4 UI code generator 4.7
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1051, 738)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.label = QtGui.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(10, 120, 51, 16))
        self.label.setObjectName("label")
        self.executeButton = QtGui.QPushButton(self.centralWidget)
        self.executeButton.setGeometry(QtCore.QRect(920, 460, 85, 27))
        self.executeButton.setObjectName("executeButton")
        self.newProjectModuleButton = QtGui.QPushButton(self.centralWidget)
        self.newProjectModuleButton.setGeometry(QtCore.QRect(150, 640, 131, 27))
        self.newProjectModuleButton.setObjectName("newProjectModuleButton")
        self.commandEdit = QtGui.QTextEdit(self.centralWidget)
        self.commandEdit.setGeometry(QtCore.QRect(250, 460, 431, 61))
        self.commandEdit.setObjectName("commandEdit")
        self.label_3 = QtGui.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(160, 250, 101, 16))
        self.label_3.setObjectName("label_3")
        self.listWidget = QtGui.QListWidget(self.centralWidget)
        self.listWidget.setGeometry(QtCore.QRect(10, 360, 131, 271))
        self.listWidget.setDragEnabled(True)
        self.listWidget.setDragDropMode(QtGui.QAbstractItemView.DragOnly)
        self.listWidget.setObjectName("listWidget")
        self.line = QtGui.QFrame(self.centralWidget)
        self.line.setGeometry(QtCore.QRect(140, 30, 20, 301))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_2 = QtGui.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(160, 20, 91, 16))
        self.label_2.setObjectName("label_2")
        self.newGlobalModuleButton = QtGui.QPushButton(self.centralWidget)
        self.newGlobalModuleButton.setGeometry(QtCore.QRect(10, 640, 131, 27))
        self.newGlobalModuleButton.setObjectName("newGlobalModuleButton")
        self.mappingsTable = QtGui.QTableWidget(self.centralWidget)
        self.mappingsTable.setGeometry(QtCore.QRect(160, 40, 881, 201))
        self.mappingsTable.setAutoFillBackground(True)
        self.mappingsTable.setAlternatingRowColors(True)
        self.mappingsTable.setCornerButtonEnabled(False)
        self.mappingsTable.setObjectName("mappingsTable")
        self.mappingsTable.setColumnCount(3)
        self.mappingsTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.mappingsTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.mappingsTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.mappingsTable.setHorizontalHeaderItem(2, item)
        self.mappingsTable.horizontalHeader().setCascadingSectionResizes(True)
        self.mappingsTable.horizontalHeader().setDefaultSectionSize(100)
        self.mappingsTable.horizontalHeader().setMinimumSectionSize(10)
        self.mappingsTable.horizontalHeader().setSortIndicatorShown(False)
        self.mappingsTable.horizontalHeader().setStretchLastSection(True)
        self.mappingsTable.verticalHeader().setVisible(False)
        self.currentContextName = QtGui.QLabel(self.centralWidget)
        self.currentContextName.setGeometry(QtCore.QRect(70, 120, 42, 15))
        self.currentContextName.setObjectName("currentContextName")
        self.treeWidget = QtGui.QTreeWidget(self.centralWidget)
        self.treeWidget.setGeometry(QtCore.QRect(160, 270, 881, 151))
        self.treeWidget.setAcceptDrops(True)
        self.treeWidget.setDragEnabled(True)
        self.treeWidget.setDragDropMode(QtGui.QAbstractItemView.InternalMove)
        self.treeWidget.setAlternatingRowColors(True)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.specialModulesList = QtGui.QListWidget(self.centralWidget)
        self.specialModulesList.setGeometry(QtCore.QRect(900, 510, 131, 81))
        self.specialModulesList.setObjectName("specialModulesList")
        self.label_4 = QtGui.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 111, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtGui.QLabel(self.centralWidget)
        self.label_5.setGeometry(QtCore.QRect(160, 430, 52, 15))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtGui.QLabel(self.centralWidget)
        self.label_6.setGeometry(QtCore.QRect(160, 460, 61, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtGui.QLabel(self.centralWidget)
        self.label_7.setGeometry(QtCore.QRect(160, 530, 71, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtGui.QLabel(self.centralWidget)
        self.label_8.setGeometry(QtCore.QRect(160, 560, 81, 16))
        self.label_8.setObjectName("label_8")
        self.nameEdit = QtGui.QLineEdit(self.centralWidget)
        self.nameEdit.setGeometry(QtCore.QRect(250, 430, 431, 23))
        self.nameEdit.setObjectName("nameEdit")
        self.descriptionEdit = QtGui.QLineEdit(self.centralWidget)
        self.descriptionEdit.setGeometry(QtCore.QRect(250, 530, 431, 23))
        self.descriptionEdit.setObjectName("descriptionEdit")
        self.dependencyEdit = QtGui.QLineEdit(self.centralWidget)
        self.dependencyEdit.setGeometry(QtCore.QRect(250, 560, 431, 23))
        self.dependencyEdit.setObjectName("dependencyEdit")
        self.deleteModuleButton = QtGui.QPushButton(self.centralWidget)
        self.deleteModuleButton.setGeometry(QtCore.QRect(690, 430, 111, 31))
        self.deleteModuleButton.setObjectName("deleteModuleButton")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1051, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpen_Project = QtGui.QAction(MainWindow)
        self.actionOpen_Project.setObjectName("actionOpen_Project")
        self.actionClose_Project = QtGui.QAction(MainWindow)
        self.actionClose_Project.setObjectName("actionClose_Project")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSave_Project = QtGui.QAction(MainWindow)
        self.actionSave_Project.setObjectName("actionSave_Project")
        self.actionSave_Context = QtGui.QAction(MainWindow)
        self.actionSave_Context.setObjectName("actionSave_Context")
        self.actionLoad_Context = QtGui.QAction(MainWindow)
        self.actionLoad_Context.setObjectName("actionLoad_Context")
        self.menuFile.addAction(self.actionOpen_Project)
        self.menuFile.addAction(self.actionSave_Project)
        self.menuFile.addAction(self.actionLoad_Context)
        self.menuFile.addAction(self.actionSave_Context)
        self.menuFile.addAction(self.actionExit)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Sched Flow Editor", None, QtGui.QApplication.UnicodeUTF8))
        MainWindow.setStatusTip(QtGui.QApplication.translate("MainWindow", "Run the current project", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Context:", None, QtGui.QApplication.UnicodeUTF8))
        self.executeButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Start the processing of these modules", None, QtGui.QApplication.UnicodeUTF8))
        self.executeButton.setText(QtGui.QApplication.translate("MainWindow", "Execute", None, QtGui.QApplication.UnicodeUTF8))
        self.newProjectModuleButton.setStatusTip(QtGui.QApplication.translate("MainWindow", "Add a new module to this project", None, QtGui.QApplication.UnicodeUTF8))
        self.newProjectModuleButton.setText(QtGui.QApplication.translate("MainWindow", "New Project Module", None, QtGui.QApplication.UnicodeUTF8))
        self.commandEdit.setToolTip(QtGui.QApplication.translate("MainWindow", "The command that will be executed. Any symbol from the above list will be substituted for it\'s mapping upon execution.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Project Modules", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.setToolTip(QtGui.QApplication.translate("MainWindow", "A list of modules that are available from the current loaded context", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Global Mappings", None, QtGui.QApplication.UnicodeUTF8))
        self.newGlobalModuleButton.setStatusTip(QtGui.QApplication.translate("MainWindow", "Add a new module to this context", None, QtGui.QApplication.UnicodeUTF8))
        self.newGlobalModuleButton.setText(QtGui.QApplication.translate("MainWindow", "New Context Module", None, QtGui.QApplication.UnicodeUTF8))
        self.mappingsTable.setStatusTip(QtGui.QApplication.translate("MainWindow", "A list of project symbols and that they translate to", None, QtGui.QApplication.UnicodeUTF8))
        self.mappingsTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Symbol", None, QtGui.QApplication.UnicodeUTF8))
        self.mappingsTable.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.mappingsTable.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "Mapping", None, QtGui.QApplication.UnicodeUTF8))
        self.currentContextName.setText(QtGui.QApplication.translate("MainWindow", "Current", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.setToolTip(QtGui.QApplication.translate("MainWindow", "A list of modules that are contained in this project", None, QtGui.QApplication.UnicodeUTF8))
        self.specialModulesList.setToolTip(QtGui.QApplication.translate("MainWindow", "A list of available special modules", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Special Modules", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Command:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Description:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Dependencies:", None, QtGui.QApplication.UnicodeUTF8))
        self.nameEdit.setToolTip(QtGui.QApplication.translate("MainWindow", "The name of the current module", None, QtGui.QApplication.UnicodeUTF8))
        self.descriptionEdit.setToolTip(QtGui.QApplication.translate("MainWindow", "The description of the current module", None, QtGui.QApplication.UnicodeUTF8))
        self.dependencyEdit.setToolTip(QtGui.QApplication.translate("MainWindow", "The IDs of the modules that must be executed before this module", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteModuleButton.setText(QtGui.QApplication.translate("MainWindow", "Delete Module", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_Project.setText(QtGui.QApplication.translate("MainWindow", "Load Project", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose_Project.setText(QtGui.QApplication.translate("MainWindow", "Close Project", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Project.setText(QtGui.QApplication.translate("MainWindow", "Save Project", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Context.setText(QtGui.QApplication.translate("MainWindow", "Save Context", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_Context.setText(QtGui.QApplication.translate("MainWindow", "Load Context", None, QtGui.QApplication.UnicodeUTF8))

