# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Wed Mar 24 17:19:39 2010
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(830, 402)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.label = QtGui.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 151, 16))
        self.label.setObjectName("label")
        self.pushButton = QtGui.QPushButton(self.centralWidget)
        self.pushButton.setGeometry(QtCore.QRect(740, 30, 85, 27))
        self.pushButton.setObjectName("pushButton")
        self.newProjectModuleButton = QtGui.QPushButton(self.centralWidget)
        self.newProjectModuleButton.setGeometry(QtCore.QRect(170, 240, 131, 27))
        self.newProjectModuleButton.setObjectName("newProjectModuleButton")
        self.commandEdit = QtGui.QTextEdit(self.centralWidget)
        self.commandEdit.setGeometry(QtCore.QRect(160, 280, 541, 51))
        self.commandEdit.setObjectName("commandEdit")
        self.label_3 = QtGui.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(160, 10, 101, 16))
        self.label_3.setObjectName("label_3")
        self.listWidget = QtGui.QListWidget(self.centralWidget)
        self.listWidget.setGeometry(QtCore.QRect(10, 30, 131, 271))
        self.listWidget.setDragEnabled(True)
        self.listWidget.setDragDropMode(QtGui.QAbstractItemView.DragOnly)
        self.listWidget.setObjectName("listWidget")
        self.projectModuleList = QtGui.QListWidget(self.centralWidget)
        self.projectModuleList.setGeometry(QtCore.QRect(160, 30, 151, 201))
        self.projectModuleList.setObjectName("projectModuleList")
        self.line = QtGui.QFrame(self.centralWidget)
        self.line.setGeometry(QtCore.QRect(140, 30, 20, 301))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_2 = QtGui.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(320, 10, 91, 16))
        self.label_2.setObjectName("label_2")
        self.newGlobalModuleButton = QtGui.QPushButton(self.centralWidget)
        self.newGlobalModuleButton.setGeometry(QtCore.QRect(20, 310, 111, 27))
        self.newGlobalModuleButton.setObjectName("newGlobalModuleButton")
        self.mappingsTable = QtGui.QTableWidget(self.centralWidget)
        self.mappingsTable.setGeometry(QtCore.QRect(320, 30, 411, 201))
        self.mappingsTable.setAutoFillBackground(True)
        self.mappingsTable.setAlternatingRowColors(True)
        self.mappingsTable.setCornerButtonEnabled(False)
        self.mappingsTable.setObjectName("mappingsTable")
        self.mappingsTable.setColumnCount(3)
        self.mappingsTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.mappingsTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.mappingsTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.mappingsTable.setHorizontalHeaderItem(2, item)
        self.mappingsTable.horizontalHeader().setCascadingSectionResizes(True)
        self.mappingsTable.horizontalHeader().setDefaultSectionSize(100)
        self.mappingsTable.horizontalHeader().setMinimumSectionSize(10)
#        self.mappingsTable.horizontalHeader().setShowSortIndicator(False)
        self.mappingsTable.horizontalHeader().setStretchLastSection(True)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 830, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpen_Project = QtGui.QAction(MainWindow)
        self.actionOpen_Project.setObjectName("actionOpen_Project")
        self.actionClose_Project = QtGui.QAction(MainWindow)
        self.actionClose_Project.setObjectName("actionClose_Project")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionOpen_Project)
        self.menuFile.addAction(self.actionClose_Project)
        self.menuFile.addAction(self.actionExit)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Sched Flow Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Global Modules", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.newProjectModuleButton.setText(QtGui.QApplication.translate("MainWindow", "New Project Module", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Project Modules", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Global Mappings", None, QtGui.QApplication.UnicodeUTF8))
        self.newGlobalModuleButton.setText(QtGui.QApplication.translate("MainWindow", "New Global Module", None, QtGui.QApplication.UnicodeUTF8))
        self.mappingsTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Symbol", None, QtGui.QApplication.UnicodeUTF8))
        self.mappingsTable.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.mappingsTable.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "Mapping", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_Project.setText(QtGui.QApplication.translate("MainWindow", "Open Project", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose_Project.setText(QtGui.QApplication.translate("MainWindow", "Close Project", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))

