#!/bin/bash

# This is a quick script to allow all of the Python UI classes to be recreated
# if any of them have been edited
pyuic4 mainwindow.ui > ui_mainwindow.py
pyuic4 newmodulewizard.ui > ui_newmodulewizard.py
pyuic4 jobprocessingwindow.ui > ui_jobprocessingwindow.py
